### ISSUE TITLE
Compile error Agatdisk

### ISSUE THREAD

**Issue by xolod79** [sintech/AGAT#1] opened 2019-08-18 22:02 UTC
Arduino: 1.8.8 (Windows 10), TD: 1.47, Board: "Teensy 3.2 / 3.1, Serial, 96 MHz (overclock), Faster, US English"

agatdisk:82: error: 'long unsigned int time' redeclared as different kind of symbol
 unsigned long time = micros();

               ^

In file included from c:\program files\arduino\hardware\tools\arm\arm-none-eabi\include\stdlib.h:11:0,

                 from C:\Program Files\Arduino\hardware\teensy\avr\cores\teensy3/WProgram.h:34,

                 from C:\Users\ALEXAN~1\AppData\Local\Temp\arduino_build_111441\pch\Arduino.h:6:

c:\program files\arduino\hardware\tools\arm\arm-none-eabi\include\time.h:59:11: note: previous declaration 'time_t time(time_t*)'

 time_t    _EXFUN(time,     (time_t *_timer));

           ^

agatdisk: In function 'void setup()':
agatdisk:190: error: invalid operands of types 'uint32_t {aka long unsigned int}' and 'time_t(time_t*) {aka long int(long int*)}' to binary 'operator-'
   Serial.println(micros() - time);

                             ^

agatdisk: In function 'void readTrack(SdFile, fileInfo, byte)':
agatdisk:310: error: assignment of function 'time_t time(time_t*)'
   time = micros();

        ^

agatdisk:310: error: cannot convert 'uint32_t {aka long unsigned int}' to 'time_t(time_t*) {aka long int(long int*)}' in assignment
agatdisk:332: error: invalid operands of types 'uint32_t {aka long unsigned int}' and 'time_t(time_t*) {aka long int(long int*)}' to binary 'operator-'
     Serial.print("Reading track: " + String(track) + "/" + String(real_track) + ", Side: " + String(track_side) + ", size: " + String(track_size)+" - ");  Serial.println(micros() - time);

                                                                                                                                                                                      ^

agatdisk:345: error: invalid operands of types 'uint32_t {aka long unsigned int}' and 'time_t(time_t*) {aka long int(long int*)}' to binary 'operator-'
     Serial.print("  after read - ");    Serial.println(micros() - time);

                                                                   ^

agatdisk:362: error: invalid operands of types 'uint32_t {aka long unsigned int}' and 'time_t(time_t*) {aka long int(long int*)}' to binary 'operator-'
     Serial.print("  after encode - ");    Serial.println(micros() - time);

                                                                     ^

agatdisk:367: error: invalid operands of types 'uint32_t {aka long unsigned int}' and 'time_t(time_t*) {aka long int(long int*)}' to binary 'operator-'
   Serial.print("after image_data array fill - ");    Serial.println(micros() - time);

                                                                                ^

agatdisk:370: error: invalid operands of types 'uint32_t {aka long unsigned int}' and 'time_t(time_t*) {aka long int(long int*)}' to binary 'operator-'
   Serial.print("after display - ");    Serial.println(micros() - time);

                                                                  ^

'long unsigned int time' redeclared as different kind of symbol

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sintech** [comment] 2019-08-19 09:35
Yes i know. It is caused by bad choice for variable name "time". 
In previous versions of arduino IDE it did not produce this error.
Will be fixed soon.

**Comment by xolod79** [comment] 2019-08-30 20:12
On Arduino studio 1.6.5 same problem. Please release binary firmware.

**Closed as completed** 2019-08-30 20:31 UTC
Labels: bug

**Comment by sintech** [comment] 2019-08-30 20:36
Fixed in a1964fc4d4e48147d3b5108cab695fd0fd3e0588
Anyway, precompilled binaries are available here: https://github.com/sintech/AGAT/releases/tag/V1.0
